### ISSUE TITLE
v1.6.2 Exit Callbacks failing on chat

### ISSUE THREAD

**Issue by autumn-cpt** [devops-csmake/csmake#34]
` EXCEPTION: Build Exit Callback '<function callbackThunk at 0x7f0151f86f50>' failed on exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 1205, in _finishUp
    callback()
  File "/usr/lib/python2.7/dist-packages/Csmake/CsmakeModule.py", line 70, in callbackThunk
    self.log.chatStartOnExitCallback(method)
  File "/usr/lib/python2.7/dist-packages/Csmake/Result.py", line 204, in chatStartOnExitCallback
    self.reporter.startOnExitCallback(name)
AttributeError: Reporter instance has no attribute 'startOnExitCallback'

**Comment by autumn-cpt** [comment]
Next issue:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 1205, in _finishUp
    callback()
  File "/usr/lib/python2.7/dist-packages/Csmake/CsmakeModule.py", line 70, in callbackThunk
    self.log.chatStartOnExitCallback(method)
  File "/usr/lib/python2.7/dist-packages/Csmake/Result.py", line 204, in chatStartOnExitCallback
    self.reporter.startOnExitCallback(name)
TypeError: startOnExitCallback() takes exactly 3 arguments (2 given)
