### ISSUE TITLE
Map with ~ on the right doesn't parse/doesn't error out

### ISSUE THREAD

**Issue by autumn-cpt** [devops-csmake/csmake#39]
`**maps= whatever -(1-1)-> ~/stuff/whatever`
Will blow up the mapper silently and proceed to map onto the content of the LHS (the identity mapping)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 1013, in _deriveResultFileFromSource
    return matcher.expand(resultre)
  File "/usr/lib/python2.7/re.py", line 281, in _expand
    template = sre_parse.parse_template(template, pattern)
  File "/usr/lib/python2.7/sre_parse.py", line 762, in parse_template
    s = Tokenizer(source)
  File "/usr/lib/python2.7/sre_parse.py", line 193, in __init__
    self.__next()
  File "/usr/lib/python2.7/sre_parse.py", line 195, in __next
    if self.index >= len(self.string):
TypeError: object of type 'NoneType' has no len()
```

**Comment by autumn-cpt** [comment]
It's definitely just because it's taking the ~ literally instead of "current home"
