### ISSUE TITLE
Deleting a file in a flow and then doing a map that would have included it fails

### ISSUE THREAD

**Issue by autumn-cpt** [devops-csmake/csmake#41]
In the scenario at hand I generate a file, move it to a new name with a new bucket, then I run a shell command to essentially "dead end" the old bucket (suggested workaround for #40), which works and I get a deleted reference....however, the deleted reference doesn't play nice with future maps that would pull it in.

```
` EXCEPTION: Attempt to execute step testing-list-raw-disks failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 734, in launchStep
    stepdict )
  File "/usr/lib/python2.7/dist-packages/Csmake/CsmakeModule.py", line 381, in _executeFileMapping
    self.mapping = fileManager.parseFileMap(statement)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 715, in parseFileMap
    result)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 399, in _dispatchMapper
    result)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 1081, in mapFilesOneToOne
    toSpec )
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 962, in _deriveResultInstanceSpec
    instance, fromSpec, toSpec )
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 996, in _deriveResultFileFromSource
    sourcere, resultre, instanceAxis = self._determineMatchingLocationFromSource(instance, fromSpec, toSpec)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 989, in _determineMatchingLocationFromSource
    sourcere = instance.getSourceRelLocationRE()
AttributeError: FileRecord instance has no attribute 'getSourceRelLocationRE'
```

**Comment by autumn-cpt** [comment]
Here's a second instance that happened after the original was deleted but we attempted to map one of its axes to a new file.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 734, in launchStep
    stepdict )
  File "/usr/lib/python2.7/dist-packages/Csmake/CsmakeModule.py", line 381, in _executeFileMapping
    self.mapping = fileManager.parseFileMap(statement)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 715, in parseFileMap
    result)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 399, in _dispatchMapper
    result)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 1081, in mapFilesOneToOne
    toSpec )
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 962, in _deriveResultInstanceSpec
    instance, fromSpec, toSpec )
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 996, in _deriveResultFileFromSource
    sourcere, resultre, instanceAxis = self._determineMatchingLocationFromSource(instance, fromSpec, toSpec)
  File "/usr/lib/python2.7/dist-packages/Csmake/FileManager.py", line 989, in _determineMatchingLocationFromSource
    sourcere = instance.getSourceRelLocationRE()
AttributeError: FileRecord instance has no attribute 'getSourceRelLocationRE'
```
I feel like perhaps the verified file is no longer there and that should be taken into account when it's the LHS

**Comment by autumn-cpt** [comment]
Problems to consider - once that file is deleted, there is no more file flow because the flow will be broken for future phases.
So there needs to be a sophisticated file tracking environment where deleted files will be gapped in for future phases (whatever that means)
Also, what does it mean for the file to dead end like that?  Do we use a different notation like `<myfile> -(1|1)-> <newfile>` to denote that this branch of the myfile container dies? or `]-(1-1)->`

**Comment by autumn-cpt** [comment]
The absorption code seems to be where the problems start.  And we end up with a FileRecord instead of a FileInstance which is what's causing the mapping resolution to barf, so that's cute.  At a minimum we need to catch this in the absorption and dead end the map source in the tracking, or throw an error, but that seems overtly over-limiting when I can imagine it being useful for lots of reasons to be able to disappear a file in mid build stream and even across phases gapped by separate executions of csmake.

**Comment by autumnpat** [comment]
PR #37  is a workaround, we really need to see this resolved properly
